### ISSUE TITLE
Question: ? icon disabled when return to menu and clicked

### ISSUE THREAD

**Issue by samumist** [qwerty1829/adapt-introjs#1]
Thanks for such a great extension, very useful.

When the course starts, the ? icon doesn't show on the menu page navigation bar. When entering into a content page, and click on the ? icon, the tutorial starts, and performs as expected from intro.js.

Returning to the menu from the content page, the ? icon shows in the navigation bar. Clicking on the ? icon, it grays out and disabled. 

And go into a content page, the ? icon stays gray and disabled.

And there's nothing in the console.

I'm wondering if this behaviour in intended?

**Environment:**
Latest Framework with sample course from the framework.

**Comment by simondate** [comment]
Thanks for the feedback.

I was planning on making it just work on content pages to begin with. I'll update to prevent the icon appearing on the menu.

**Comment by simondate** [comment]
Should now be fixed. If you are much of a coder could you check my implementation. Not really keen on getElements() being called every time you click the button.

**Comment by samumist** [comment]
sorry, I'm not a real coder but more of a user. But I'll test out the new patch and report back.

**Comment by samumist** [comment]
Yes, it fixed on the menu. 
I'm looking forward to your implementation for the icon only showing on the designated page rather than all content pages.
